---
- name: Install Jenkins and OpenJDK 17 (on debian)
  hosts: all
  become: yes
  tasks:

    # OpenJDK 17
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install fontconfig and openjdk-17-jre
      apt:
        name:
          - fontconfig
          - openjdk-17-jre
        state: present

    # Jenkins
    - name: Add Jenkins keyring
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Add Jenkins repo
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        state: present
        filename: jenkins

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    # Start and enable Jenkins service
    - name: Ensure Jenkins service is started and enabled
      service:
        name: jenkins
        state: started
        enabled: yes

